# Inspired from the .travis.yml in
# https://github.com/davidchall/homebrew-hep/

language: ruby
rvm: 2.3

cache:
  directories:
    - "$HOME/Library/Caches/Homebrew"
    - "$HOME/.cache/Homebrew"
    - "$HOME/.cache/pip"
    - "$HOME/.gem/ruby"

install:
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)"
  - if [ -f ".git/shallow" ]; then
      travis_retry git fetch --unshallow;
    fi
  - HOMEBREW_REPOSITORY="$(brew --repo)"
  - sudo chown -R "$USER" "$HOMEBREW_REPOSITORY"
  - git -C "$HOMEBREW_REPOSITORY" reset --hard origin/master
  - brew update || brew update
  - HOMEBREW_TAP_DIR="$(brew --repo "$TRAVIS_REPO_SLUG")"
  - mkdir -p "$HOMEBREW_TAP_DIR"
  - rm -rf "$HOMEBREW_TAP_DIR"
  - ln -s "$PWD" "$HOMEBREW_TAP_DIR"
  - export HOMEBREW_DEVELOPER="1"
  - if test "$TRAVIS_PULL_REQUEST" != "false"; then
      export UPSTREAM_PULL_REQUEST=$TRAVIS_PULL_REQUEST;
    fi

  - export HOMEBREW_BINTRAY_USER="maelvalais"
  - export TAP_BOTTLE_DOMAIN="https://dl.bintray.com/touist"
  - ulimit -n 1024

  # the official test-bot won't let you run inside TravisCI, so we use
  # davidchall's one. David's test-bot cannot push the commit using
  # Oauth github + https (only ssh) so I use my own.
  - brew tap maelvalais/test-bot

  - aws s3 sync s3://homebrew-touist-travis/shared ~/shared

script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      brew test-bot --ci-testing;
    else
      brew test-bot --ci-pr;
    fi
  - mv *.bottle*.* ~/shared 2>/dev/null || echo "==> No bottle created here"

jobs:
  include:
  # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
    - os: linux
      env: OS=x86_64_linux
      before_install:
        - yes '' | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        - export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
        - export PATH="$HOME/.local/bin:$PATH" # for `aws` (awscli)
        - pip install --user awscli
#    - os: osx
#      osx_image: xcode9.1
#      env: OS=high_sierra
#    - os: osx
#      osx_image: xcode8
#      env: OS=sierra
#    - os: osx
#      osx_image: xcode6.4
#      env: OS=el_capitan
    - stage: deploy
      if: branch = master && type != pull_request
      os: linux
      before_install:
        - yes '' | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
        - export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH"
        - export PATH="$HOME/.local/bin:$PATH" # for awscli
        - pip install --user awscli
      script:
        - mv ~/shared/* .
        - brew test-bot --ci-upload --git-name=maelvalais --git-email=mael.valais@gmail.com --bintray-org=touist --verbose --dry-run
        - brew test-bot --ci-upload --git-name=maelvalais --git-email=mael.valais@gmail.com --bintray-org=touist --verbose
      after_success:
      # Clean the bucket
        - aws s3 rm s3://homebrew-touist-travis --recursive
      

# --tap=touist/touist is not necessary because we already set HOMEBREW_TAP_DIR
after_success:
  - aws s3 sync ~/shared s3://homebrew-touist-travis/shared
