# Inspired from the .travis.yml in
# https://github.com/davidchall/homebrew-hep/

language: ruby
rvm: 2.3

cache:
  directories:
# "$HOME/Library/Caches/Homebrew" seems to be used in linux
# also and poses the permissions problem below.
    - "$HOME/Library/Caches/Homebrew"
    - "$HOME/.cache/Homebrew"
    - "$HOME/.cache/pip"
    - "$HOME/.gem/ruby"

# if I don't do umask, the formula touist.rb is rw-rwr-- instead of rw-r--r--
# after brew tap touist/touist
# See https://github.com/cybertk/homebrew-gitlab-runner/pull/2
install:
  - export TRAVIS_COMMIT="$(git rev-parse --verify -q HEAD)";
  # This step will make sure aws, brew are installed and
  # that we are in a folder symlinked (in one way or the other)
  # to $(brew --repo "$TRAVIS_REPO_SLUG"). If we don't do that,
  # the git push won't work.
  - |
    if [ "${TRAVIS_OS_NAME}" = "osx" ]; then
      HOMEBREW_REPOSITORY="$(brew --repo)";
      sudo chown -R "$USER" "$HOMEBREW_REPOSITORY";
      git -C "$HOMEBREW_REPOSITORY" reset --hard origin/master;
      brew update || brew update;
      HOMEBREW_TAP_DIR="$(brew --repo $TRAVIS_REPO_SLUG)";
      mkdir -p "$HOMEBREW_TAP_DIR";
      rm -rf "$HOMEBREW_TAP_DIR";
      ln -s "$PWD" "$HOMEBREW_TAP_DIR";
    else
      # Fix the permission problem on linux (664 instead of 644)
      umask 022;
      yes '' | sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)";
      export PATH="/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH";
      export PATH="$HOME/.local/bin:$PATH"; # for `aws` (awscli)
      pip install --user awscli;
      # Fix a `brew doctor` error on "config" scripts
      sudo rm -f /home/travis/.phpenv/shims/php-config;
      sudo rm -f /opt/pyenv/shims/*-config;
      sudo rm -f /usr/local/clang-3.9.0/bin/llvm-config;
    fi
  - export UPSTREAM_BOTTLE_KEEP_OLD=true
  - export HOMEBREW_DEVELOPER="1"
  - export HOMEBREW_BINTRAY_USER="maelvalais"
  - export TAP_BOTTLE_DOMAIN="https://dl.bintray.com/touist"
  - ulimit -n 1024

  # the official test-bot won't let you run inside TravisCI, so we use
  # davidchall's one. David's test-bot cannot push the commit using
  # Oauth github + https (only ssh) so I use my own.
  - brew tap maelvalais/test-bot

  - aws s3 sync s3://homebrew-touist-travis/${TRAVIS_BUILD_NUMBER} ~/shared

script:
  - brew test-bot
  - cp *.bottle*.* ~/shared 2>/dev/null || echo "==> No bottle created here"

jobs:
  include:
  # https://docs.travis-ci.com/user/reference/osx/#OS-X-Version
    - os: linux
      env: OS=x86_64_linux
#    - os: osx
#      osx_image: xcode9.1
#      env: OS=high_sierra
#    - os: osx
#      osx_image: xcode8
#      env: OS=sierra
#    - os: osx
#      osx_image: xcode6.4
#      env: OS=el_capitan
    - stage: deploy
      if: branch = master && type != pull_request && type != tag
      os: linux
      env: OS=any_linux
      script:
        # For --ci-upload, we MUST be in the folder of the tap,
        # not in ~/build/<slug>
        - brew tap touist/touist;
        - cd "$(brew --repo $TRAVIS_REPO_SLUG)";
        - git fetch --unshallow
        - if cp -v ~/shared/* . ; then
            brew test-bot --ci-upload --git-name=maelvalais --git-email=mael.valais@gmail.com --bintray-org=touist --verbose;
          else
            echo "==> No bottle downloaded, cannot run --ci-upload";
          fi
      after_success:
        # Clean the bucket
        #- aws s3 rm s3://homebrew-touist-travis/${TRAVIS_BUILD_NUMBER} --recursive
      
# --tap=touist/touist is not necessary because we already set HOMEBREW_TAP_DIR
after_success:
  - aws s3 sync ~/shared s3://homebrew-touist-travis/${TRAVIS_BUILD_NUMBER}